### ISSUE TITLE
Line 11 command not found

### ISSUE THREAD

**Issue by Ralus-oss** [utsanjan/Tsunami-Bomber#5]
Tsunami.sh: line 11 command not found

**Comment by utsanjan** [comment]
I've already written in the ReadMe that "wget" and "python3" are Prerequisites of the script. It seems that wget is not installed in your system. Try installing it first, it should work. Good luck.

**Comment by Ralus-oss** [comment]
Ok tks,
But this is only for +91?

Not for all county ?

Pada tanggal Kam, 29 Jul 2021 08.44, Utsanjan Maity <
***@***.***> menulis:

**Comment by utsanjan** [comment]
Currently, the script supports only +91, may get more updates for international support in the future.
